### ISSUE TITLE
בעיית סינטקס

### ISSUE THREAD

**Issue by alonkit** [yossigil/safot#26]
https://github.com/yossigil/safot/blob/b3f72bddcf83b37819ed195464f0451fa2c21a9e/lisp.tex#L495

 (a (b c) d) מהרשימה שנוצרה
ניתן ליצור שתי עצים שונים
     /\                                 /\
   /\  d                             a  /\
a   /\                                 /\   d
   b   c                              b   c
and this seems like a problem

**Comment by yossigil** [comment]
Cannot read what you wrote.
