### ISSUE TITLE
Implement defun

### ISSUE THREAD

**Issue by yossigil** [yossigil/safot#347]

**Comment by DorYeheskel** [comment]
@yossigil 
Done.
## Notes:
* Files changes: eval.cc
* Added the support of __cons__ in the evaluate atomic function + Added test for it.
* Added the support of __set__ in the evaluate atomic function + Added test for it.
* Passing test for complex cons/set, e.g mirror: "(cons (cdr x) (car x))" which require to evaluate both $2$ and $3$ and then cons.
* Validated the a-list: in case of defun the same function name for couple of times, 
  it saves all of them in the a-list and the latest function that defined, located in the begging of the a-list.
* Passed all the new unit tests of defun/ndefun.
* Evaluate is finally ready for testing.
