### ISSUE TITLE
Test files for evaluate-primitive

### ISSUE THREAD

**Issue by yossigil** [yossigil/safot#349]
Create test file evaluate-primitive-test.cc with separate tests for all primitive functions.
Use the parser to read an expression, send it to eval, and eval should call eval-primitive,
or maybe other test strategy.

**Comment by yossigil** [comment]
The tests must fail, since the function is not implemented yet. Perhaps I will ask @OfirMarkowitz1 to implement the function. This is what people call test driven design (TDD)

**Comment by DorYeheskel** [comment]
Done. 
Waiting for a code review.
