### ISSUE TITLE
Test for apply

### ISSUE THREAD

**Issue by yossigil** [yossigil/safot#350]
Choose at first very simple function: say mirror.
You should also try recursive functions, but this is trick.

**Comment by DorYeheskel** [comment]
Can I take this issue ? @yossigil 
I will create: apply-test.cc , and later (Me or Ofir) will implement the **apply** (TDD).

**Comment by yossigil** [comment]
Sure, go ahead.

**Comment by DorYeheskel** [comment]
Done.

**Comment by yossigil** [comment]
I looked at the tests. Good job. You need to make sure that the semantics is right. See examples I wrote in the t-fluent.cc
