### ISSUE TITLE
Test of defun (ndefun)

### ISSUE THREAD

**Issue by yossigil** [yossigil/safot#351]
Make sure that the correct data is placed on the a-list.

**Comment by DorYeheskel** [comment]
@yossigil 
Done.
## Notes:
* Files changes: t-apply.cc, Makefile
* Files added: t-defun.cc
* Added unit tests for ndefun, e.g: mirror function as describe in the book, complex functions, etc.
* Added unit tests for defun - complex function calls which require to evaluate parameters (evaluate-list) before binding in apply.
* Fixed apply unit tests.

**Comment by yossigil** [comment]
thanks

**Comment by yossigil** [comment]
The test cases are very well written, good job.

**Comment by DorYeheskel** [comment]
I already did a test that distinguish between defun and ndefun, see above.

Please see the notes that I wrote in each of the issues in Project.
