### ISSUE TITLE
Structured errors with integer exceptions only.

### ISSUE THREAD

**Issue by yossigil** [yossigil/safot#353]
Perhaps a duplicate of #372

**Comment by DorYeheskel** [comment]
What is the diffrent between this issue to: "Implement function error! Introduce varieties, to make it easy to print messages" ?
@yossigil

**Comment by DorYeheskel** [comment]
Done.

**Comment by yossigil** [comment]
Yes. Good thanks. I will open a small issue for the printouts

**Comment by yossigil** [comment]
I did not find the recursive tests, but I am not sure I looked everywhere.

**Comment by yossigil** [comment]
10x
