### ISSUE TITLE
Separate production and overhead code

### ISSUE THREAD

**Issue by yossigil** [yossigil/safot#357]
Make sure the production code is minimal, does not use C++ streams, nor any other library. Not even stdio.h

**Comment by DorYeheskel** [comment]
Done.

**Comment by yossigil** [comment]
I am not sure this is done. For example, production code should not use C++ output functions.

**Comment by DorYeheskel** [comment]
@yossigil 
Do you have any example ? I didn't use any C++ output functions or other functions at all.

**Comment by yossigil** [comment]
in the debugging parts, I think in io.cc

**Comment by yossigil** [comment]
I messed this a bit with #388
