### ISSUE TITLE
Compilation failed in the latest version

### ISSUE THREAD

**Issue by DorYeheskel** [yossigil/safot#361]

**Comment by yossigil** [comment]
Please supply list of errors

**Comment by DorYeheskel** [comment]
1)
in function `bind(S, S, S)':
undefined reference to `error(char const*)'

2)
main.o: in function `REPL()':
undefined reference to `Parser::supply(char const*)'

3)
ast-test.cc:252:6: error: call of overloaded ‘supply(const char [88])’ is ambiguous252 |  "\n");

**Comment by yossigil** [comment]
Should be easy to fix; add dummy functions error and find the problem with supply.
