### ISSUE TITLE
Finish Fluentons

### ISSUE THREAD

**Issue by yossigil** [yossigil/safot#376]
This includes rac, rdc, less and snoc.

Rac is like car except that it does no checking at all.

**Comment by yossigil** [comment]
add tests in t-fluentos.cc

**Comment by DorYeheskel** [comment]
@yossigil 
Done.
## Notes:
* Implemented: rac, rdc, less
* Added unit tests for: rac, rdc, less
* All the unit tests passed.

**Comment by yossigil** [comment]
great. Feel free to close issues yoursefl.
