### ISSUE TITLE
Finish up REPL

### ISSUE THREAD

**Issue by yossigil** [yossigil/safot#380]
in 00.cc (currently).
Two caveats:

1.  Make sure you restore the a-list in exceptions.
2.  Make parsing of two lines, ie. continuations. See parser.h

**Comment by DorYeheskel** [comment]
@yossigil 
Done.
## Notes:
* Added support for multi-line input in the shell - all implemented in C.
The input stop after '\n' and only if the parentheses of the input are balanced.
* Restored the a-list in REPL in case of exception thrown by error function.
