### ISSUE TITLE
Implement REPL and simple interactive environment: all in 00.cc.

### ISSUE THREAD

**Issue by yossigil** [yossigil/safot#381]

**Comment by DorYeheskel** [comment]
@yossigil 
Done.
## Notes:
* Added support for multi-line input in the shell - all implemented in C.
The input stop after '\n' and only if the parentheses of the input are balanced.
* Restored the a-list in REPL in case of exception thrown by error function.

**Comment by yossigil** [comment]
Seems to be done indeed.
