### ISSUE TITLE
Full testing of eval in C.

### ISSUE THREAD

**Issue by yossigil** [yossigil/safot#382]

**Comment by DorYeheskel** [comment]
@yossigil 
# Finished evaluation function + tested eval + all tests passed:
### eq:
* Added the support of _eq_ in evaluate_atomic_function in **eval.cc**.
* Added tests to t-evaluate-primitive.cc to check it + passed.

### error: 
* Added the support of _error_ in evaluate_atomic_function (e.g: "(error 'some_msg)") in **eval.cc**.
* Added tests to t-evaluate-primitive.cc to check it + passed.

### evaluate_cond:
* Fixed the evaluate_cond function in eval.cc, which had a small bug.
* Tested my old test of evaluate cond, the test that check if 
  cond set the variables names as in normal evaluation in the a-list and passed (**t-eval-cond.cc**).

### Tests of evaluate cond:
* Passed all.

### Tests of evaluate primitive using parse (not in C): 
* Passed all. 
  (some of them needed a small fix with the logic)

### New tests of Eval:
* Added the file: **t-eval.cc**
* Full testing of eval function, including evaluation of 
  different functions with different params, 
  and testing different errors cases, etc.

### Tests:
* All the evaluations tests in the project passed.

**Comment by DorYeheskel** [comment]
(continue the message above)

### defun/ndefun:
* Added the support of the built-in functions defun/ndefun in eval.cc + tested.

### lambda/nlambda:
* Added the support of the built-in functions lambda/nlambda in eval.cc + tested.

**Comment by yossigil** [comment]
Are there unit tests for these? Easiest is to take the files that LaTeX generates and feed them to mini-lisp, for example, 
`./mini-lisp < ../00.kernel.9.lisp`

**Comment by DorYeheskel** [comment]
Testing done in C (the issue: "Full testing of eval in C"). 


About testing:
./mini-lisp < ../00.kernel.9.lisp, 

This will be in [issue](https://github.com/yossigil/safot/issues/381).
