### ISSUE TITLE
Implement, test and check the Mini-Lisp code in the book.

### ISSUE THREAD

**Issue by yossigil** [yossigil/safot#383]
Start from the book. There are bugs. You may need to correct them.
Keep track of changes.
Try to place code back in book.
Check file lisp.tex

**Comment by yossigil** [comment]
You must implement eval and test it.

**Comment by DorYeheskel** [comment]
@yossigil 
Done.

# Notes:
### eval implementation
* I wrote the notes of evaluation [here](https://github.com/yossigil/safot/issues/382).

### Mini-Lisp code:
* Added the file: **t-book.cc**
  It includes the Mini-Lisp code from the book, tested **only** with parse and eval (not C).
* It includes:
  * All the atomic functions.
  * All the built-in functions. 
  * Functions from the book: mirror,  zcar, etc.
* All the tests passed.

### Fixed the book:
* Changed the file: **lisp.tex**
* Bugs:
  * (car '(b.a))  ⇒ B (fix: ⇒ B.A )
  * (cdr '(a.b))  ⇒ B (fix: ⇒ NIL )
  * (cons 'b nil) ⇒ NIL  (fix: ⇒ (B) )
  * (nlambda f (x y) (y x))  (fix: removed the "f")

**Comment by DorYeheskel** [comment]
(continue from above)

### Tests of running eval on eval:
* Done.
* All of them passed. (in t-book.cc)
