### ISSUE TITLE
Managing Globals and Locals.

### ISSUE THREAD

**Issue by yossigil** [yossigil/safot#384]
But the tests do not work...
I rethought this: we need two kinds of a-list. One that is used for local definitions, and one for global sets.
It is not so trivial since the list have to be concatenated.

let g be the global and l be the local. Then the list is something like this:
l ->B1-->B2->B3->S1->S2->NIL
where B1 and B2 and B3 are local bindings and S1, S2 are global sets.
Now, pointer g pints to S1.
If there is another global set, say S3, You cannot put right before S1, since l will not see it.
But, you cannot put it

**Comment by yossigil** [comment]
Test cases:

1. Function setting variables, which remain set after the function returns. Without this one cannot modify the primitive function set.
2. Same as 1, but the function aborts. All sets made before the abortion should prevail.

**Comment by DorYeheskel** [comment]
@yossigil 
Done.
Implemented, tested and passed.

### Test cases:
**Case 1: No error:**
```lisp
(cond (
    (null (set 'a 'x))  'x)  
    (null (set 'b 'x))  'x)  
    (atom (set 'c 'x))  'x)  
)
```
Both a, b, c,  all defined in the alist - lookup for each of them return 'x.

**Case 2: Error:**
```lisp
(cond (
    (null (set 'a 'x))  'x)  
    (null (set 'b 'x))  'x)  
    (atom (error 'c 'x))  'x)  
)
```
Both a, b, c,  are **not** defined in the alist - lookup for each of them throw an UNDEFINED error.
