### ISSUE TITLE
Validate and create flow tests for all the Mini-lisp Evaluate functions from the book - exist, lookup, apply, evaluate,  evaluate_cond, evaluate_list etc.

### ISSUE THREAD

**Issue by DorYeheskel** [yossigil/safot#387]
Run:
./mini-lisp < evaluate_book.lisp

**Comment by DorYeheskel** [comment]
@yossigil 
This is the last issue in: [project](https://github.com/yossigil/safot/projects/1).

**Comment by yossigil** [comment]
Indeed, but this is also the crux of the project. Showing that the function `evaluate` written in mini-lisp works correctly, i.e., that it can be used to replace eval. The demo is of writing a compiler/interpreter for the language in the language itself. The challenge is making it the shortest possible. The book tries to do it. The software project is to show that the implementation is correct.

It may be necessary to edit the excerpts in the book. Hopefully, not so many.

**Comment by DorYeheskel** [comment]
@yossigil 
During the testing of the mini-lisp book, I noticed that there is a small mistake in the image of evaluate - 
`apply-eager-primitive` may call evaluate too.

This is the fix:
![image](https://user-images.githubusercontent.com/38854355/126033250-d18aeaba-7d6a-4193-8b7f-d60a38db3a23.png)

**Comment by yossigil** [comment]
If you have the time, go ahead pleas and fix it in `lisp.tex`, sould be easy.

**Comment by DorYeheskel** [comment]
OK.

**Comment by DorYeheskel** [comment]
@yossigil 
### Update:
I tested the following functions, using the lisp code from the book:
✔️ exists
✔️ lookup
✔️ is-primitive
✔️ bind
✔️ apply-eager-primitive
✔️ apply-trivial-primitive

**Comment by yossigil** [comment]
Great. Did you see my automatic extracts?

**Comment by DorYeheskel** [comment]
Yes.

I'm using the code that generated to teadmill.lisp.

**Comment by yossigil** [comment]
Look for files named:

heavy_check_mark exists.lisp
heavy_check_mark lookup.lisp
heavy_check_mark is-primitive.lisp
heavy_check_mark bind.lisp
heavy_check_mark apply-eager-primitive.lisp
heavy_check_mark apply-trivial-primitive.lisp

**Comment by yossigil** [comment]
Great issue management.

**Comment by DorYeheskel** [comment]
### Updates:

Validation script: 
./Mini-Lisp.ShellTestFramework/test/flow/test_book_evaluate.py

Still working on more complex inputs to be sure evaluate functions are correct.

**Comment by DorYeheskel** [comment]
### Updates:
Validation is now less complex, thanks too: #442

**Comment by DorYeheskel** [comment]
@yossigil 
Done.

Few **important** notes about the Mini-lisp validation are written below.
# Tests:
**Validation tests:** 
The [flow tests](https://github.com/yossigil/safot/blob/master/Mini-Lisp.ShellTestFramework/test/flow/test_book_evaluate.py) done for each of the Mini-lisp's evaluate functions, using the ShellTestFramework I created & pytest.
* Inputs files [here](https://github.com/yossigil/safot/tree/master/Mini-Lisp.ShellTestFramework/test/inputs/test_book_evaluate).
* Golden files [here](https://github.com/yossigil/safot/tree/master/Mini-Lisp.ShellTestFramework/test/golden/test_book_evaluate).

**Flow details:**
Each of the flow tests, done by the following steps:
* Generate the latest lisp files from the book (using make clean+all [here](https://github.com/yossigil/safot/tree/master/Mini-Lisp.BookValidator/Mini-Lisp.Inputs)).
* Open communication with the mini-lisp executable in Mini-Lisp.Chic (using the IPC I created [here](https://github.com/yossigil/safot/tree/master/Mini-Lisp.ShellTestFramework/framework/lib)).
* Feed the shell with all the [relevant](https://github.com/yossigil/safot/blob/master/Mini-Lisp.ShellTestFramework/test/flow/test_book_evaluate.py#L37) lisp files (all the evaluate functions).
* Feed the shell with the input file ([e.g](https://github.com/yossigil/safot/blob/master/Mini-Lisp.ShellTestFramework/test/inputs/test_book_evaluate/test_evaluate_2.lisp.in)).
* Communicate with the mini-lisp process and write all the outputs from the shell to out file.
* Compare out file with golden file ([e.g](https://github.com/yossigil/safot/blob/master/Mini-Lisp.ShellTestFramework/test/golden/test_book_evaluate/test_evaluate_2.lisp.out)).
* If the files are identical then the test passed, else failed and show diffs.

**Run:**
To run all the validation tests, run the following command:
`./Mini-Lisp.ShellTestFramework/bin/run_all_tests.sh  flow`

Before that, make sure that python3 and pytest are installed:
`make install -C  ./Mini-Lisp.ShellTestFramework/build/`


# Notes:
During the validations, I found some bugs - both in the C implementation and in the Mini-Lisp book and fixed them, and also I added few enhancements which are necessary for the validation and for the mini-lisp usage.

### Enhancements:
* Added the support of **stack trace** in the C implantation (notes [here](https://github.com/yossigil/safot/issues/442#issuecomment-898910790)).
* Created an [API ](https://github.com/yossigil/safot/blob/master/Mini-Lisp.ShellTestFramework/framework/lib/flow_test_framework.py)(used by the flow tests), allows the user to run and communicate with the mini-lisp process via Python, feeding the shell with input file and get the results to output file. 
The main advantage is that the mini-lisp process won't stop after each feeding from the input file and thus the environment (alist) remain the same (or grows), so we can load a lot of input files with new functions and continue the feeding using those new functions (the validation tests done exactly like this).

### Bug fixes (Mini-lisp book):
* Fixed **evaluate-cond** (notes [here](https://github.com/yossigil/safot/commit/daa278eda1bf0453126c438bf47d8e9c69939a18))
* Fixed **apply-eager-atomic** (notes [here](https://github.com/yossigil/safot/commit/a1aa727639b2cd469632ddc33e417698d56b0d13))

### Bug fixes (C implementation):
* Fixed a bug in local binding during the returning from recursion calls + refactoring some parts of the code (notes [here](https://github.com/yossigil/safot/issues/449#issue-975555194))

**Comment by yossigil** [comment]
Great work. Looking forward for a demo
