### ISSUE TITLE
Small testing framework for stdin, stdout and stderr.

### ISSUE THREAD

**Issue by yossigil** [yossigil/safot#388]
A couple of bugs in the REPL function were noticed, and **quickly** fixed.  But, there is no systematic way of testing whether bugs of this sort exist or not.

Interfaces for redirection: 
###  Modified reader interface
```C++ 
#ifndef READ_H
#define READ_H
extern String read(); // Only function in production mode
#ifndef PRODUCTION // Testing adds overhead, which should not be part of production
namespace Reading {  // For readability; Read::from("(car x)") is better than reader_set_source
  extern from(String);  // Once called, you cannot go back to stdin, but you can set another source if you like 
}
#endif // PRODUCTION
#endif // READ_H
```
###   Modified out interface including printing and erroring
```C++ 
#ifndef OUT_H
#define OUT_H
// All  existing functions used by the production code.
#ifndef PRODUCTION // Testing adds overhead, which should not be part of production
namespace Printing { // Better name is Write, but we have to be consistent with REPLY
   extern void record(); /** Start recording into a new clean buffer, if buffer exists, clean it */
   extern String playback();  /** Rerturn current contents of buffer */ 
};
namespace Erroring { // Name could (and probably would) change.
   extern void record(); /** Start recording into a new clean buffer, if buffer exists, clean it */
   extern String playback();  /** Rerturn current contents of buffer */ 
};
#endif // PRODUCTION
#endif // OUT_H
```

### Sketch of implementation, `reader.cc`

```C++ 
#include  "read.h"

String read() {
      #ifndef PRODUCTION // Modify the read in case of redirection
if (redirected) return source
     #endif
.... // Original code
}


#ifndef PRODUCTION // Implementation of redirection
static boolean redirected= false;
static const char *source;
namespace Reading {
 void from(String s) { source = s; }// Beware of constness
#endif
}
```

### Sketch of implementation, `out.cc`

```C++ 
#include "out.h"

#ifndef PRODUCTION // Not part of production code.
namespace Printing { // The recording infrastructure for stdout
    char *tape = 0;
    int head = 0;
    int n ;  /*  How many bytes were allocated  */
    void record()  {
       if (tape != 0) free(tape); 
        tape = malloc(n = 7); /* No checking, if tests fail due to memory allocation, only god can help. */
       head = 0;
    }
    String playback() {  return tape;  }
   boolen record(String s) {
       n += strlen(s);  // Better if write strlen ourselves, unless this was already done.
       tape = realloc(&tape, n);
       strcpy(tape + head, s);  // Better if write strcpy ourselves, probably in the atoms module
       head += strlen(s);
    }
    record(String s) {
    }
};
#endif
```

### Stderr redirection:

- Generally, the same as stdout redirection
- Caveat, function `perror` printing to stderr. Use       char *strerror(int errnum); instead.
- We may want a class/Type since code is similar to printing

### utility testing function 

TBD

**Comment by DorYeheskel** [comment]
@yossigil 
Done.

### Notes:
1. Testing in : *t-repl.cc*.
2. Interface for io: using built-in functions of google test.

**Comment by yossigil** [comment]
Several issues, I think:

1. It is important to preserve the REPL structure, it would go into the book
2. the tests are fragile; they assume *debug* output.

**Comment by DorYeheskel** [comment]
@yossigil 
### Answers:
1. I didn't change the structure of REPL, I just added 1 `input` argument, that if it '\0', REPL get the input from user.
2. Why ? the tests stores everything came from stdout and stderr to buffers and test them.
3. `kind` and `where` fields are not swapped. I have a lot of tests that check stderr with these messages. See: t-repl.cc file.

**Comment by DorYeheskel** [comment]
@yossigil 

1. Fixed the test to ignore the debugging printing in 00.cc.
2. kind and where fields are checked.

See: **t-repl.cc** file - half of it check stdout and half stderr.

**Comment by yossigil** [comment]
Great; but take note that the test is still fragile against minor changes to formatting. I will see what I can do about this. 
Also, the REPL must be restored. I will try my hand at this.

**Comment by yossigil** [comment]
We need to reinstate 00.cc

**Comment by yossigil** [comment]
OOPS, I think you did it...
