### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by OfirMarkowitz1** [yossigil/safot#393]

**Comment by OfirMarkowitz1** [comment]
I finished all the formatting issues on the jquery terminal - syntax highlighting, highlighting matching parentheses, autocompletion.
I face two problems right now:
1. Regarding the the syntax/parentheses highlight, I use the formatting system of the jquery terminal, which uses brackets. The use of brackets for formatting conflicts with the new grammar, in which a pair is surrounded by brackets, instead of parentheses. I tried the jquery terminal API to deal with this issue but didn't manage to get it right. Also, I found some example code which supposedly deals with this issue, and hoping that I will resolve with this reference, and if not, I will come up with an algorithm my self.
2. I can't push the changes to git yet. Hopefully, I'll resolve this issue today.

**Comment by yossigil** [comment]
I cross my fingers. Keep up posted.

**Comment by OfirMarkowitz1** [comment]
The first problem is solved.

**Comment by yossigil** [comment]
Ok, let us close this issue; further GUI issues should be created as they pop
