### ISSUE TITLE
Parser Test

### ISSUE THREAD

**Issue by OfirMarkowitz1** [yossigil/safot#404]

**Comment by yossigil** [comment]
Just copy, paste and translate the C reference implementation

**Comment by yossigil** [comment]
Specifically, the testing code. Not the implementation, which should be done by delegating to external library

**Comment by yossigil** [comment]
Which commit did close this?

**Comment by OfirMarkowitz1** [comment]
I closed some of the issues in review by accident because I thought they
are in done

**Comment by OfirMarkowitz1** [comment]
I reopened them. Sorry for that.

**Comment by yossigil** [comment]
NP!
