### ISSUE TITLE
Create Tutorial Folder

### ISSUE THREAD

**Issue by yossigil** [yossigil/safot#416]

**Comment by twyair** [comment]
would creating a submodule folder be ok? i don't remember what you decided... anyway i think it'd be much more organized this way as the relevant branches, commits and PRs would be on their own repo

**Comment by yossigil** [comment]
It is more concise, definitely, but it would require students and ta’s to use  a couple of repos. Not so good IMHO

**Comment by twyair** [comment]
ok. I created a tutorials folder.
