### ISSUE TITLE
Ofir - Learn Mini-lisp C architecture thoroughly

### ISSUE THREAD

**Issue by OfirMarkowitz1** [yossigil/safot#425]

**Comment by yossigil** [comment]
if you wish, we can go over this tomorrow. The reason this is important, is that there are plenty of gotchas encountered in the C implementation.  No need to reinvent the wheel.

Fortunately for JavaScript, most modules are short and avoid  C idiosyncrasies.  Even betters, about half the modules do not require a JavaScript equivalent.

**Comment by yossigil** [comment]
Great
