### ISSUE TITLE
Mini-LISP JS - Consistent names in Pair.js

### ISSUE THREAD

**Issue by OfirMarkowitz1** [yossigil/safot#428]
@yossigil - In JS, using the same name for a method and a field creates a conflict, therefore, I can't use car and cdr as field names. My suggestion is adding underscore for the field name in this particular case, or even making it a convention across the JS project - field names always begin with underscore.

**Comment by yossigil** [comment]
- You could use upper case, can't you?
- I do not know JS, but what is said [here](https://flaviocopes.com/javascript-namespaces/) seems to suggest that field names can be distinct from global names.

**Comment by OfirMarkowitz1** [comment]
I wasn't referring to a conflict between global and field names, but
between method and field names of the same class.
I much rather use a convention of underscore at the beginning of every
field name, if it's ok with you.

**Comment by yossigil** [comment]
Go ahead! Submit a commit that close this triviality.

**Comment by yossigil** [comment]
If this is a general JS convention, sure!
If not, I am ready to be convinced.

**Comment by OfirMarkowitz1** [comment]
OK, I will fix and close this

**Comment by OfirMarkowitz1** [comment]
Even better solution - apparently on JS, if a field is private, there is no
conflict, and I wanted the fields to be private anyway.

**Comment by yossigil** [comment]
Please submit a commit that closes this issue.

**Comment by yossigil** [comment]
Thanks.
