### ISSUE TITLE
Mini-LISP JS Parser - Symbol defined exactly as in the C tokenizer

### ISSUE THREAD

**Issue by OfirMarkowitz1** [yossigil/safot#430]

**Comment by yossigil** [comment]
Should be easy, but critical. We need to be able to use weird symbols such as `~!,` and `12`. Crucial for assignments to extend mini lisp, e.g., with arithmetic.

**Comment by OfirMarkowitz1** [comment]
Done

**Comment by yossigil** [comment]
Next time, tag the commit with issue number, e.g., 
```git comment -m "fixes #430"``` 
or if it just deals with the issue, something like ```git comment -m "more work on #430"```

if you do so, you will save yourself the trouble of updating the issue; if you write `fix` or `close` this will also automatically close the issue.

**Comment by OfirMarkowitz1** [comment]
All of the issues I opened, beside the one involving the C project
compilation error, is in the project's sprint, in the "Ready for review"
column.
I was meaning to close them after your review is over without rejections. I
can close them immediately when I put them for review, if it's preferable.
Thanks for the advice on git! It's very helpful.

**Comment by yossigil** [comment]
I checked the code. Not right still. Please do something like `[^()\[\].;]`
There are six or so reserved characters used as tokens. Spaces are ignored. So are comments.
I *beg* that you examine the tokenizer in C. It is all there, and would have saved all this interaction.

**Comment by yossigil** [comment]
*Exactly* means _**exactly**_

**Comment by yossigil** [comment]
Take a look at the PEGS file.

**Comment by OfirMarkowitz1** [comment]
Firstly, I did examine the Tokenizer h and cc files carefully editing the
pegjs file.
Secondly, I think you made a mistake - you replaced the quote sign e.g. ',
with semicolon, e.g. ; - correct me if I'm wrong.
Now for the essence of the matter, the pattern  [^()\[\].\'] doesn't work
in PEG.js.
That's why I used unicode ranges, the only thing that I found that seemed
to work.
ASCII didn't work, only unicode, i.e. [\u0021-\u0026].
If you check out the unicode table, you will find that this is equivalent
to what you were suggesting, aside from the semicolon mistake.

Ofir

**Comment by OfirMarkowitz1** [comment]
I managed to shorten the unicode a bit by using [^...] as you suggested, by still needed to use unicode, and needed to added all the unprintable and whitespace characters to the pattern in order for it to work.

**Comment by yossigil** [comment]
Please give reference to the commit you did

**Comment by OfirMarkowitz1** [comment]
84dc4a3

**Comment by OfirMarkowitz1** [comment]
I managed to improve this further. Turns out the problem was only because I
have to add the whitespace, unprintable and non-ASCII characters to the
Symbol regex.
See commit - d48f25c

**Comment by OfirMarkowitz1** [comment]
It would be better to find a way for the "_" variable regex, e.g. the
characters to ignore, to have precedence over the Symbol,
such that we wouldn't need to add those characters to the Symbol regex.
Simply putting the characters to ignore rule above the Symbol rule doesn't
seem to do it (even though rules order makes difference in PEG grammars).

**Comment by yossigil** [comment]
Or, perhaps some very special Unicode classes/categories?
