### ISSUE TITLE
Mini-LISP JS - Copy/Add the C Parser tests

### ISSUE THREAD

**Issue by OfirMarkowitz1** [yossigil/safot#432]
@yossigil - Should I copy or add?

**Comment by yossigil** [comment]
Focus mostly on the failures. Try to find a clever way to do the editing so that you do not do all the many tests by hand. Editor macros, record and play should help. If you acquire the technique, it may help in other cases.

**Comment by OfirMarkowitz1** [comment]
In t-parser.cc:
TEST(Parser, Pair) {
  feed("a.b");
  ASSERT_NE(Status::ready, status());
  ASSERT_NE(Status::reject, status());
  EXPECT_EQ(Status::accept, status());
}

TEST(Parser, PairInList) {
  feed("(a.b)");
  ASSERT_NE(Status::ready, status());
  ASSERT_NE(Status::reject, status());
  EXPECT_EQ(Status::accept, status());
}

Both tests seems wrong to me. The status in "Pair" should be "reject", because this is not how you write a pair in Mini-LISP - 
See table in page 34 in the book, namely car and cdr examples. car of (b.a) is B, and cdr is A, so that means that (b.a) is a dotted-pair of B and A. The string "b.a" should not be excepted as a pair.
For the same reason, "PairInList" is not a pair in a list but just a dotted-pair. The string "((a.b))" is referring to a pair in a list.

**Comment by yossigil** [comment]
?

**Comment by OfirMarkowitz1** [comment]
I'm currently working on it. While observing the C parser tests, I found
some discrepancies between it and the JS Parser.
This issue is very important and thanks for insisting upon it.
It's unclear to me what is exactly happening in some cases because the
parser tests only check if the string was accepted/rejected,
but fail to make sure that the S expression received matches the one
expected.
For example:

TEST(Parser, Pair) {
  feed("a.b");
  ASSERT_NE(Status::ready, status());
  ASSERT_NE(Status::reject, status());
  EXPECT_EQ(Status::accept, status());
}

I'm not sure what the resulting S expression will be by simply observing
the test.
Should (car 'a.b) return A?
I can't seem to understand from the book.

In Common-LISP:
(car 'a.b) throws an error, because a.b is considered an atom.
(car '(a.b)) returns A.B, because '(a.b) is considered an atom inside a
list.
(car '(a . b)) returns A, because whitespace between the period and the
letters suggests that it's an actual pair.
This means that at least in Common-LISP, period can be part of an atom, as
well as the quote mark.

The behaviour of the C parser in these cases isn't clear to me.
Your help would be appreciated.

**Comment by yossigil** [comment]
The grammar is in parser.cc. It gives a link to a the LL grammar on line.
In short, I think it is something like this:
```
S->(S.S)
S->LIST
S->Quote
S->Atom

List -> ( ManyS )
ManyS -> Empty
ManyS -> S manyS.

Quote -> ‘ S




```

I think this excludes A.B; forces (A.B) to be a dotted pair, not a list.


There is no atom a.b.

I hope this helps

**Comment by OfirMarkowitz1** [comment]
As I mentioned, the JS parser is consistent with this behavior, and the C
implementation is not, according to the tests.

**Comment by yossigil** [comment]
I think the JS parser rejects A.B, the C implementation accepts it. The problem is that it makes some expressions impossible to write; e.g., consider expression a.b.c, then depending on associativity, it has one meaning, but it is impossible to override the default associativity with parenthesis.... 


Bug in design, I will have to revise it.

**Comment by OfirMarkowitz1** [comment]
Do you want to define associativity rules so avoiding parenthesis would be possible? For example:
1. a.b => (a . b)
2. a.b.c => (a . (b . c))
3. (a.b).c => ((a . b) . c)
In these examples, we use right associativity, and can override it using parentheses.
I'm not sure if that's what you meant.

**Comment by yossigil** [comment]
Yes, it is possible; but then, we have an issue with the parenthesis, since (a.b).c is a cons of a singleton list that contains the pair a.b together with the atom c. This is easy to resolve with square brackets; perhaps this is the way I should go about this;

**Comment by OfirMarkowitz1** [comment]
Yes, I see what you mean.
