### ISSUE TITLE
Mini-LISP JS Parse - Throw an error admonishing the user upon parser failure to recognize expression

### ISSUE THREAD

**Issue by OfirMarkowitz1** [yossigil/safot#433]

**Comment by yossigil** [comment]
Not sure why is this critical. Let's put it on hold for now.

**Comment by OfirMarkowitz1** [comment]
> Not sure why is this critical. Let's put it on hold for now.

This is the error handling issue. If the name is confusing, I can change it.

**Comment by OfirMarkowitz1** [comment]
In Atom.js:
	car() {
    // Convert this to a throw of an S expression, and only an S expression.
		throw `CAR: ${this.value} is not a list`
	}

I should still throw an exception but one containing an S expression instead. Did I understand you correctly?

**Comment by yossigil** [comment]
Yes, exactly. See the C++ code; it does throw an exception object, but it is the S expression. in Javascript you may include this expression as a field.

**Comment by OfirMarkowitz1** [comment]
Ok, thanks!
