### ISSUE TITLE
yarn.lock? Should it be git managed?

### ISSUE THREAD

**Issue by yossigil** [yossigil/safot#435]

**Comment by OfirMarkowitz1** [comment]
It's not even appearing in my local folder. Maybe try to just erase it? Perhaps we should replace this issue with an issue of the installation process, and if after jest installation this file appears we can add it to gitignore.

**Comment by yossigil** [comment]
@OfirMarkowitz1

**Comment by OfirMarkowitz1** [comment]
I thought I answered you about this, sorry.
When I install jest, it does not produce a yarn.lock file, so I suspect
that with the right installation configuration, we won't need to be dealing
with it.

**Comment by OfirMarkowitz1** [comment]
> @OfirMarkowitz1

See my comment above

**Comment by yossigil** [comment]
Make sure it is in .gitignore

**Comment by OfirMarkowitz1** [comment]
Done.

**Comment by yossigil** [comment]
10x
