### ISSUE TITLE
Test mini-lisp in Chic with files with code samples.

### ISSUE THREAD

**Issue by yossigil** [yossigil/safot#436]
This is essential for testing.
It is related, but not exactly the same as #388

**Comment by yossigil** [comment]
We need a loop with this Pseudo Code in Python/ Bash/javascript, whatever. 

```
For file f in Inputs/*.lisp:
  If file has function name, read the file, feed it to lisp.
  Otherwise,  the file represents an S-Expression do the same, read the file feed it to lisp.
  Verify that everything is OK.
```

For now, we have no real checking that everything is OK, but it would be added. Checking means:

1. If it is an S expression, there should be another file, with the expected output.
2. More generally, if the file contains several S expressions, then the expected output file should contain all results.
3. If the file is a function definition, then there should be files with test cases for these S-expressions.

The nice thing about the framework is that  you do not have to compile anything to add more tests. This will save much time and effort. The down side is that time and effort should be invested to implement this.

**Comment by DorYeheskel** [comment]
Done.

I wrote a small documentation at the beginning of the [script](https://github.com/yossigil/safot/blob/7c54a97d20499df361dbff8fc6c5256a09018b47/Mini-Lisp.BookValidator/run.sh).

**Comment by yossigil** [comment]
I took a look. Seems as if there are four variables you set, and then run a command. In general, I am happy to incorporate many tools to assist in the environment, including Python and shell script. For this shell script, it is very natural to write it in a Makefile.

**Comment by yossigil** [comment]
Why not Make? I am not reopening, just want to understand

**Comment by DorYeheskel** [comment]
In my opinion, it is better to run a script then makefile, if the purpose is running a full flow.

**Comment by yossigil** [comment]
Not sure, but that’s leave it at that for now. You have one important issue to finish:  #448. Let’s focus on this one.
