### ISSUE TITLE
Fix the interactive environment

### ISSUE THREAD

**Issue by DorYeheskel** [yossigil/safot#438]

**Comment by DorYeheskel** [comment]
Fix the interpreter, allow it to compile multi-lines and EOF (e.g: ./mini-lisp < file.lisp  must success) + test it using the new test framework.

**Comment by yossigil** [comment]
Please introduce a test case to demonstrate the problem, before submitting a fix. If you do so, I may be able to fix it by a little tweak.

**Comment by DorYeheskel** [comment]
Done.

Test cases [here](https://github.com/yossigil/safot/blob/master/Mini-Lisp.ShellTestFramework/test/unit/test_mini_lisp_shell.py#L57), [here](https://github.com/yossigil/safot/blob/master/Mini-Lisp.ShellTestFramework/test/unit/test_shell_test_framework.py#L6) and also in the [flow](https://github.com/yossigil/safot/blob/master/Mini-Lisp.ShellTestFramework/test/flow/test_book_evaluate.py#L8) tests which demonstrate multi-lines inputs from files.

**Comment by yossigil** [comment]
Thanks
