### ISSUE TITLE
Stack trace in C implementation

### ISSUE THREAD

**Issue by DorYeheskel** [yossigil/safot#442]
This issue regarding to #387 but can be use for other purposes.
Each time that we call a function (evaluate-atomic / apply), we want to print the name of the function, the args and the results.

**Comment by yossigil** [comment]
@OfirMarkowitz1 

A better way to do it is a stack dump. To do so, you push into the a-list, prior to calling a function stack trace records.

There are two kinds of such a records:
1. Function invocation record; this record is pushed into the stack (aka a-list),  immediately after the function body is fetched from the a-list.
2. Argument evaluation record: this record contains the name of formal parameter, the argument that matches, before and after evaluation.  You push this record just prior to evaluating any argument. If you call a normal function, the two values, before and after evaluation, are the same, don’t worry about this.


Recall that the stack is an a-list. Each item in it is a pair, with identifier as the car, and value as the cdr. The two kinds of records are similar. 
1. The identifier of a function activation record, is the special atom ‘recurse’.
2. The identifier of a argument evaluation record is ‘argument’ 

Both names may change later. but it is important that they are fixed and do not depend on function name nor argument name. 


The records are, as usual, S-expression;
1. The value bound to the special name recurse, is a dotted pair. It is exactly the same pair as found in the a-list when the function f is found.  So, if f if a function that compares the car of its two arguments, then it is originally stored in the a-list as (f.(lambda (x y) (eq (car x) (car y))). What we store in the function activation record is this s-expression (recurse. (f.(lambda (x y) (eq (car x) (car y)))).

1. The value bound to argument evaluation record is a simple three items list: formal name, formal before evaluation and formal after evaluation.

**Comment by yossigil** [comment]
@OfirMarkowitz1 #399 ;


Here is some more info; in the C/ JavaScript implementation once you hit the error function, you call a stack dump function; the function should traverse the a-list, printing these records; the contents of the records will probably change a bit; e.g., it seems we do not need all the information in the argument evaluation record. We have it in binding, right?

**Comment by OfirMarkowitz1** [comment]
> Argument evaluation record: this record contains the name of formal parameter, the argument that matches, before and after evaluation. You push this record just prior to evaluating any argument.

How can I push this record prior to the argument's evaluation, if this record contains the argument's evaluation result?

**Comment by OfirMarkowitz1** [comment]
@yossigil
In the scheme you drew for me, you wrote that there should a printing of an S expression, which represents the body, after the formals have been replaced by the actuals.
1. Is this necessary? It may be have some edge cases, thus not sure if it's easy to implement.
2. When in the body there's a call to an eager primitive/lambda, should we replace the formal with the actual preceded by quote? Then the S expression's evaluation would be equivalent to the body, which is kind of cool.
3. It seems that this should be implemented with a sort of lazy evaluation where you evaluate the body without actually calling any function, only replacing the formals with the actuals.

**Comment by DorYeheskel** [comment]
Done.

### Examples:
**Atomic functions:**
```lisp
> (cdr (car 'a))
Traceback (most recent call last):
        From function CDR:
                Args: (CAR (QUOTE A))
        From function CAR:
                Args: A
Error [CAR] in A
>
```
**Mirror function:**
```lisp
> (defun mirror (x) (cons (cdr x) (car x)))
MIRROR

> (mirror 'a)
Traceback (most recent call last):
        From function MIRROR:
                Args: (A)
        From function CONS:
                Args: (CDR X)
                Args: (CAR X)
        From function CDR:
                Args: A
Error [CDR] in A
>
```

**Exists function:**
```lisp
> (defun exists (x xs) (cond ((null xs) xs)((eq x (car xs)) t)(t (exists x (cdr xs)))))
EXISTS

> (exists 'a '(a b))
T

> (exists 'a 'a)
Traceback (most recent call last):
        From function EXISTS:
                Args: (A A)
        From function COND:
                Args: (((NULL XS) XS) ((EQ X (CAR XS)) T) (T (EXISTS X (CDR XS))))
        From function EQ:
                Args: X
                Args: (CAR XS)
        From function CAR:
                Args: A
Error [CAR] in A
> 
```

**Error example:**
```lisp
> (cons 'a (error 'my_err))
Traceback (most recent call last):
        From function CONS:
                Args: (QUOTE A)
                Args: (ERROR (QUOTE MY_ERR))
        From function ERROR:
                Args: MY_ERR
Error [MY_ERR] in (ERROR (QUOTE MY_ERR))
>    
```

**Comment by yossigil** [comment]
> @yossigil
> In the scheme you drew for me, you wrote that there should a printing of an S expression, which represents the body, after the formals have been replaced by the actuals.
> 
> 1. Is this necessary? It may have some edge cases, thus not sure if it's easy to implement.
No, it is not not essential; this was the big design. I think it is cool. 

> 2. When in the body there's a call to an eager primitive/lambda, should we replace the formal with the actual preceded by quote? Then the S expression's evaluation would be equivalent to the evaluation of the body, which is kind of cool. 

You got it; this is the actual binding!

> 3. It seems that this should be implemented with a sort of lazy evaluation where you evaluate the body without actually calling any function, only replacing the formals with the actuals.

No, it is much simpler than that; you write a recursive function that takes an S-expression and a list of substitutions, and applies them. Here is an example: > (defun mirror (x) (cons (cdr x) (car x)))
MIRROR
```lisp
> (mirror 'a)
Traceback: (mirror ‘a) => (mirror [a]) ; note the syntax of function application to evaluated arguments
                    => (cons (car [a]) (cdr [a])) ; note the syntax again
                    => (car [a])
Error [CDR] in A
>

**Comment by OfirMarkowitz1** [comment]
> No, it is much simpler than that; you write a recursive function that takes an S-expression and a list of substitutions, and applies them. Here is an example: > (defun mirror (x) (cons (cdr x) (car x)))
> MIRROR

The problem is that you don't always want to replace the formal atom, for instance:
```Lisp
(defun foo (x) 'x)
```
Inside the body, the formal atom is inside a quote, so this function actually ignores the given argument and always returns X,
so the substitution would be wrong in this case:

```Lisp
(foo 'a) ;After the wrong substation the body would be (QUOTE A), while the function returns X
```

**Comment by OfirMarkowitz1** [comment]
Asking again:
> Argument evaluation record: this record contains the name of formal parameter, the argument that matches, before and after evaluation. You push this record just prior to evaluating any argument.

How can I push this record prior to the argument's evaluation, if this record contains the argument's evaluation result?

**Comment by yossigil** [comment]
You are right; the wording and the design were buggy. What you really need to do is be to be able to print a good stack dump in the case that there is an error during the evaluation of an argument to a function, prior to invoking it, for example
(Mirror (car ‘a) b) should abort for two different reasons; there are too many arguments, and the evaluation of the first argument is buggy. Recall the implementation of the evaluation engine; it evaluates the arguments in order, and then does the invocation. You must leave on the a-list enough information to be able to print the correct error, which is something like “error in evaluating argument x’ of function mirror.

To be able to do that, you have to maintain on the a-list the function activation record, which is very much like the lambda/nlambda expression, except that it includes the function name. This record should contains the names of the parameters and their unevaluated arguments. It is a bug to include the evaluated value of the arguments at this point. 

Now, the argument evaluation record is slightly different; it should tell you, when you traverse the a-list; that you are in the midst of evaluating argument ‘x’ for the function; fortunately, you do no need to name the function; the next function activation record in the list defines precisely the invoking function. 

But, this is not the end of it; there might be another record you need to keep on the a-list; one that says that you have finished evaluating the arguments to the function, and you are now in the process of evaluating the body of the function. This record is trivial; it contains absolutely no information; call it EXECUTE; it is a fixed record for all functions. 

to print a dump; you traverse the a-list; if you encounter  an EXECUTE record first, you know that you are in the process of computing some function; to know the name of the function; you will have to continue traversing until you find an INVOCATION record. This record will tell you much about the function currently executing.

If however you encounter an ARGUMENT record, you will know that you are in the midst of computing an argument to a function; the name of the function can again be found by traversing the list up to the next INVOCATION record. You know that the current argument has failed.

**Comment by yossigil** [comment]
Can I suggest a slightly different output which is more compact? 
Done.

### Examples:
**Atomic functions:**
```lisp
> (cdr (car 'a))
Traceback (most recent call last):
        CDR[CAR (QUOTE A)]
        CAR[A]
          ** Error CAR on A
>
```
**Mirror function:**
```lisp
> (defun mirror (x) (cons (cdr x) (car x)))
MIRROR

> (mirror 'a)
Traceback (most recent call last):
        MIRROR[A]
        CONS[(CDR X), (CAR X)]
        CDR[A]
        ** Error CDR on A
>
```
The idea is that you use square brackets and comma to make it clear which function invocation you do.
