### ISSUE TITLE
Define precisely the set of accepted character in the book, and all implementations

### ISSUE THREAD

**Issue by OfirMarkowitz1** [yossigil/safot#443]

**Comment by yossigil** [comment]
@OfirMarkowitz1 , do you believe that you can fix this in the JS implementation?

**Comment by yossigil** [comment]
I checked the tokeniser.c file, and it seems to be doing precisely this. I still need to fix the book. But, @OfirMarkowitz1, if you can fix this in the JS, or open an issue for the JS.

**Comment by yossigil** [comment]
#430 seems to resolve the above comment

**Comment by OfirMarkowitz1** [comment]
It always worked this way in the JS. Accept that I think you intentionally forgot the dot character which is also a token, both in the Tokenizer.h and in the JS implementation. It has to be because it is reserved for separating the car from the cdr in a pair.

**Comment by yossigil** [comment]
## Context Free Grammar of S-Expressions
```
S ::= 'S
S ::= [ S . S ]
S ::= ( Ss )
Ss ::=  ε
Ss ::= S Ss
S  ::= A
A ::= [a-zA-Z0-9!"#$%&*+,\-/:<=>?@\\\^ _`{|}~]*
```

This is the grammar and the lexical part.

**Comment by OfirMarkowitz1** [comment]
> A ::= [a-zA-Z0-9!"#$%&*+,\-/:<=>?@\\\^ _`{|}~]*

The regex should end with + instead of *, other wise

**Comment by OfirMarkowitz1** [comment]
Closed it by accident

**Comment by yossigil** [comment]
why can't we close it for good?

**Comment by OfirMarkowitz1** [comment]
We can, as far as I'm concerned.

**Comment by yossigil** [comment]
Need to revise the text, and only then the implementations.

**Comment by OfirMarkowitz1** [comment]
I'm not following. What revise is needed?

**Comment by yossigil** [comment]
Make 100% sure that this is the grammar.

**Comment by OfirMarkowitz1** [comment]
There are parser tests which does exactly that.

**Comment by yossigil** [comment]
If this is done, then close this issue
