### ISSUE TITLE
Fix the dotted pair in the JS implementation

### ISSUE THREAD

**Issue by yossigil** [yossigil/safot#447]
See explanation in #444; see further parser.c; it has a link to the grammar; our official grammar is [this](   https://www.cs.princeton.edu/courses/archive/spring20/cos320/LL1/)

**Comment by yossigil** [comment]
I suggest the following simple grammar: 
```
S ::= Atom | List | Pair
Atom ::= id // please restrict input to ASCII only, no Unicode support
List :: = ( Items ) 
Items ::= S Items | ‘’
```

**Comment by yossigil** [comment]
The Chic implementation should also be fixed according to this grammar

**Comment by OfirMarkowitz1** [comment]
I'm not sure I understand.
1. The Pair definition is missing. 
2. The quote using ' is not supported.
3. "id" is not defined. Should it mean all characters but ```'.( )[ ]```?
4. I guess the comments and characters that should be ignored, never gets to the parser (ignored by the tokenizer).

**Comment by yossigil** [comment]
I fixed the grammar to include pairs and quotes. 

Comments are not part of the *grammar*. Grammar only cares about tokens. Comments are ignored by the grammar, and hence are not tokens.

The elimination of spaces, comments, and the separation of characters into identifiers, or the other tokens, is done by the tokeniser. So, the tokens we have are (, ), [, ., ], and an identifier. 

The tokeniser should be configured to deal with ASCII, not UTF support for now. And IDs are as defined in the corrected grammar modulo glitches.

**Comment by OfirMarkowitz1** [comment]
I changed so the grammer accordingly. I haven't tried to use a different computer to push the changes yet. That's why you do not see any commits. I'll work on it today. Hopefully the git problem will get solved today.

**Comment by yossigil** [comment]
How is it going?

**Comment by OfirMarkowitz1** [comment]
I solved the problem
