### ISSUE TITLE
Lisp Evaluate on Lisp Evaluate

### ISSUE THREAD

**Issue by DorYeheskel** [yossigil/safot#448]
This is the final issue in [project](https://github.com/yossigil/safot/projects/1).
This must be done after the full validation of all the lisp evaluate functions #387.

All the validation tests in #387 **must** be the same tests for this issue too.

For example, test_1 which test the lisp evaluate function, must be the same test for the lisp evaluate function which evaluate by the lisp evaluate function.

**Comment by yossigil** [comment]
Eager to see you excelling

**Comment by yossigil** [comment]
Great progress. How do you identify memory exhaustion?

**Comment by DorYeheskel** [comment]
### Updates:
After I found the real cause of the problem, I added a workaround fix in the C code (#456 ), so now much more complex s-expressions (evaluate on evaluated) successfully evaluated, and the progress continue :)

**Comment by yossigil** [comment]
So, what was the problem???

**Comment by DorYeheskel** [comment]
@yossigil 

Finally, the Lisp Evaluate on Lisp Evaluate passed all the flow tests I did, and successfully evaluate itself !!!

To fully understand what I did here, please read the doc [here](https://github.com/yossigil/safot/tree/master/Mini-Lisp.ShellTestFramework#evaluateonevaluate).

**Comment by yossigil** [comment]
Great. So, can we schedule a submission? Asked differently, would you like to improve anything before you submit?

**Comment by DorYeheskel** [comment]
@yossigil 
I'm ready to submit the [project](https://github.com/yossigil/safot/projects/1).

Thanks,
Dor

**Comment by yossigil** [comment]
I think we need installation instructions

**Comment by DorYeheskel** [comment]
[Here](https://github.com/yossigil/safot/tree/master/Mini-Lisp.ShellTestFramework#installation).

**Comment by yossigil** [comment]
Superb. So, let's submit it!

**Comment by DorYeheskel** [comment]
Great!
From my side, the [project ](https://github.com/yossigil/safot/projects/1) is ready and I am ready to submit it :)

Thanks for everything,
Dor

**Comment by yossigil** [comment]
great. So, can we meet on Tuesday?

**Comment by DorYeheskel** [comment]
Yes

**Comment by yossigil** [comment]
Sent you an invite
