### ISSUE TITLE
Refactor alist + Fix bug

### ISSUE THREAD

**Issue by DorYeheskel** [yossigil/safot#449]
During the validation of Lisp evaluate #387 , I found some issues in my current C implementation of alist.

Handling of local/global variables need a fix, because each time that we do binding, we need to undo all the local variables we bound.
In simple cases it was ok, but for more complex examples (such as Lisp evaluate_cond), it failed.

For example:
```lisp
1. (defun evaluate-cond(test-forms a-list)
2.   (cond ((null test-forms) nil) 
3.         ((evaluate (car (car test-forms)) a-list) 
4.         (evaluate (car (cdr (car test-forms))) a-list)) 
5.       (t (evaluate-cond (cdr test-forms) a-list)))) 
```
Call: `(evaluate-cond '((a b)) '(b.t a.t))`
Step 1:  bound A-LIST with (b.t a.t).
Step 3:  evaluate first eval it's args including A-LIST with (b.t a.t) and second it try to evaluate A 
-> lookup bound A-LIST with (b.t a.t)  and didn't find A
-> lookup (recursive) bound A-LIST with (a.t) and did find A
Step 4: evaluate first eval it's args including A-LIST with **(a.t)** because this was the last definition in our a-list, and then failed to evaluate b --> Undefined error (bug)

**Comment by DorYeheskel** [comment]
Done.

**Comment by yossigil** [comment]
I am not sure I this integer crunching makes sense to me. It has to be done with pointers, but I give in... If you have tests, I may be able to fix this some day.
