### ISSUE TITLE
Can't push to origin

### ISSUE THREAD

**Issue by OfirMarkowitz1** [yossigil/safot#450]
I'm unable to push my changes to origin for some reason.
Seems that my access expired:

<img width="1194" alt="Screen Shot 2021-08-22 at 21 45 13" src="https://user-images.githubusercontent.com/63195552/130366445-51bf8e52-90ad-4e6c-997b-70a15ad53c9e.png">

**Comment by yossigil** [comment]
I have no idea what’s going on. I did not commit or touch the git rep for two weeks or so. @DorYeheskel, are you experiencing the same problem.

@OfirMarkowitz1 do you think you can try this from another computer? @twyair, do you have the same problem?

**Comment by OfirMarkowitz1** [comment]
I'll try

**Comment by yossigil** [comment]
Resolved?

**Comment by OfirMarkowitz1** [comment]
Yes
