### ISSUE TITLE
Add documentation to ShellTestFramework

### ISSUE THREAD

**Issue by DorYeheskel** [yossigil/safot#455]
Add README.md with documentation of: lib, api, tests, flow, usage, etc.

**Comment by yossigil** [comment]
+1

**Comment by DorYeheskel** [comment]
[Done](https://github.com/yossigil/safot/tree/master/Mini-Lisp.ShellTestFramework).

**Comment by yossigil** [comment]
Thanks. We are closing in, right?

**Comment by DorYeheskel** [comment]
Yes.

**Comment by yossigil** [comment]
@OfirMarkowitz1 - this is where the testing framework is done
