### ISSUE TITLE
Mini-LISP bug in dynamic binding of lambda parameters

### ISSUE THREAD

**Issue by OfirMarkowitz1** [yossigil/safot#464]
Consider the following REPL flow:
```LISP
> (defun reduce (xs f init)
	(cond 	((null xs) init)
			(t (f (car xs) (reduce (cdr xs) f init)))))
(LAMBDA (XS F INIT) (COND ((NULL XS) INIT) 
> (defun map (xs f) (reduce xs (lambda (x y) (cons (f x) y)) nil))
(LAMBDA (XS F) (REDUCE XS (LAMBDA (X Y) (CONS (F X) Y)) NIL))
> (map '([a.b] [c.d]) (lambda (x) (car x)))
Traceback (most recent call last):
	MAP[([A . B] [C . D]), (LAMBDA (X) (CAR X))]
	REDUCE[([A . B] [C . D]), (LAMBDA (X Y) (CONS (F X) Y)), NIL]
	COND[((NULL XS) INIT), (T (F (CAR XS) (REDUCE (CDR XS) F INIT)))]
	F[[A . B], ^(REDUCE (CDR XS) F INIT)]
	REDUCE[([C . D]), (LAMBDA (X Y) (CONS (F X) Y)), NIL]
	COND[((NULL XS) INIT), (T (F (CAR XS) (REDUCE (CDR XS) F INIT)))]
	F[[C . D], NIL]
	CONS[^(F X), Y]
	F[^X]
	** Error MISSING in ((LAMBDA (X Y) (CONS (F X) Y)) X)
>
```
This error is caused by the fact that the binding of the F formal of REDUCE is done *after* the binding of the F formal of MAP. If we gave those two formals different names, this collision won't occur:
 ```LISP
> (defun reduce (xs f init)
	(cond 	((null xs) init)
			(t (f (car xs) (reduce (cdr xs) f init)))))
(LAMBDA (XS F INIT) (COND ((NULL XS) INIT)
> (defun map (xs g) (reduce xs (lambda (x y) (cons (g x) y)) nil))
(LAMBDA (XS G) (REDUCE XS (LAMBDA (X Y) (CONS (G X) Y)) NIL))
> (map '([a.b] [c.d]) (lambda (x) (car x)))
(A C)
> 
```
It doesn't make since that the name of the formals of REDUCE and MAP would matter, so this behavior is surely a bug, which leaves us to decide whether we want a lambda to be exposed to the arguments of the body in which they appear.
I think the behavior should be invariant to formal's names, and whether a lambda is passed as an argument to another lambda or called directly..
I think that if the lambda is exposed to its environment, it's effectively a closure, and there should be a way to do this with single-list dynamic binding.
On the other hand, if we decide against this, it would mean that the behavior in the second block of code will end with an UNDEFINED error instead of a result, and i'm not sure there would a way to implement map using reduce, which seems weird to me.

**Comment by yossigil** [comment]
This is not a bug; this is a feature of dynamic binding I think

**Comment by OfirMarkowitz1** [comment]
I don't think it makes sense that different formal names would yield different results. For instance, if I named a lambda REDUCE using defun, should I bear in mind the fact that I used F, and try to avoid a conflict when using REDUCE? If the NULL function is a lambda and not a primitive, does it make sense for the user to remember what is it's formal's name? He can type NULL and press enter, and see the formal name, but it doesn't make sense to me that one would have to do that.

**Comment by OfirMarkowitz1** [comment]
Another example:
```LISP
> ((lambda (x) ((lambda (f x) (f x)) (lambda (y) x) 'a)) 'b)
A
> 
```
This should yield B and not A because the LAMBDA given as an argument is not declared inside its caller, and the X in its body should be bound to B when calling it.

**Comment by OfirMarkowitz1** [comment]
> This is not a bug; this is a feature of dynamic binding I think

Perhaps you mean "dynamic *scoping*"?

**Comment by yossigil** [comment]
dynamic scoping, yes.

**Comment by OfirMarkowitz1** [comment]
OK, I'm leaving it :)
